# Generated by Django 5.0.9 on 2024-09-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subject.subject",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterModelTable(
            name="course",
            table=None,
        ),
    ]
