# Generated by Django 5.0.9 on 2024-09-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_question_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_options",
                to="quiz.question",
            ),
        ),
    ]
