# Generated by Django 5.0.9 on 2024-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_answeroption_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentquizattempt",
            name="score",
            field=models.FloatField(),
        ),
    ]
