# Generated by Django 5.0.9 on 2024-09-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_studentquizattempt_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="time_limit",
            field=models.IntegerField(default=30),
        ),
    ]
